#!/bin/sh
HOSTNAME="127.0.0.1"
PORT="3306"
USERNAME="mapping"
PASSWORD="pam@mogu"
DBNAME="mapping"
TABLENAME="requestTimesLog"
use_db_sql="use ${DBNAME}"
mysql -h${HOSTNAME} -P${PORT} -u${USERNAME} -p${PASSWORD} -e "${use_db_sql}"
#get the data
requestKeyArr=["Service:HotelSearchService |wew" \
"Tavisca110|GetHotelSearchResult" "Tavisca110|GetSingleHotelData" "Tavisca110|GetMultiHotelsData" \
"Tavisca100|GetHotelSearchResult" "Tavisca100|GetSingleHotelData" "Tavisca100|GetMultiHotelsData"]
for str in ${requestKeyArr[@]};do
        content=$(mktemp /tmp/tmp.XXXXXXXXXX) || exit 1
        echo > content
        echo | grep $str /home/ec2-user/app/x-search/xshell-0.1.0-SNAPSHOT/log/stdout.log  >> content
        lines= wc -l content || 0
        supplierid= echo str | cut -d "|" -f 1 || ""
        serviceName= echo str | cut -d "|" -f 2 || ""
        echo $str
        echo $serviceName
        echo $lines
        #insert into database
        insert_sql="insert into ${TABLENAME}(requestSupplierId,requestUrl,count) 
         values(${supplierid},${serviceName},${lines})"
        mysql -h${HOSTNAME} -P${PORT} -u${USERNAME} -p${PASSWORD} ${DBNAME} -e "${insert_sql}"
done
